ingredients = {
"Apple":{"calories":95},
"Banana":{"calories":105},
"Broccoli":{"calories":55},
"Brown rice":{"calories":216},
"Chicken breast":{"calories":165},
"Egg":{"calories":78},
"Greek yogurt":{"calories":100},
"Ground beef":{"calories":250},
"Oatmeal":{"calories":150},
"Orange":{"calories":62},
"Salmon":{"calories":200},
"Spinach": {"calories":7},
"Sweet potato":{"calories":103},
"Tuna":{"calories":99},
"Whole wheat bread":{"calories":69},
"Avocado":{"calories":160},
"Blueberries":{"calories":84},
"Carrots":{"calories":52},
"Cheddar cheese":{"calories":114},
"Eggs":{"calories":78},
"Green beans":{"calories":44},
"Ground turkey":{"calories":185},
"Peanut butter":{"calories":190},
"Quinoa":{"calories":222},
"Strawberries":{"calories":46},
"Turkey breast":{"calories":140},
"Whole wheat pasta":{"calories":175},
"Almonds":{"calories":164},
"chicken": {"calories": 350},
"Samosas": {"calories":150},
"Aloo gobi": {"calories":150 },
"Tandoori chicken": {"calories":200},
"Chana masala": {"calories":150 },
"Palak paneer": {"calories":200},
"Biryani": {"calories":300 },
"Dosa": {"calories":150},
"Butter chicken": {"calories":300 },
"Dhokla": {"calories":100 },
"Mutter paneer": {"calories":200 },
"Pulao": {"calories":250 },
"Kulfi": {"calories":150 },
"Idli": {"calories":100},
"Chicken tikka": {"calories":200 },
"Vada pav": {"calories":300 },
"Sushi ":{"calories":180 },
"Ramen ":{"calories":400 },
"Udon ":{"calories":300 },
"Tempura ":{"calories":200 },
"Takoyaki ":{"calories":150 },
"Teriyaki ":{"calories":300 },
"Yakitori ":{"calories":150 },
"Sashimi ":{"calories":80 },
"Bento Box ":{"calories":600 },
"Miso Soup ":{"calories":50 },
"Kimchi ":{"calories":50 },
"Bibimbap ":{"calories":330 },
"Japchae ":{"calories":250 },
"Bulgogi ":{"calories":250 },
"Tteokbokki ":{"calories":150 },
"Jajangmyeon ":{"calories":500 },
"Galbi ":{"calories":200 },
"Gimbap ":{"calories":300 },
"Samgyeopsal ":{"calories":200 },
"Mandu ":{"calories":100 },
"Haemul Pajeon ":{"calories":300 },
"Nakji Bokkeum ":{"calories":150 },
"Jeon ":{"calories":150 },
"Naengmyeon ":{"calories":150 },
"Sundubu Jjigae ":{"calories":300 },
"Ddukbokki ":{"calories":150 },
"Pyeonyuk ":{"calories":200 },
"Gamjatang ":{"calories":400 },
"Seolleongtang ":{"calories":300 },
"Soondae ":{"calories":250 },
"Margherita Pizza ":{"calories":250},
"Spaghetti Bolognese ":{"calories":400},
"Lasagna ":{"calories":600},
"Fettuccine Alfredo ":{"calories":600},
"Risotto ":{"calories":400},
"Caprese Salad ":{"calories":200},
"Osso Buco ":{"calories":500},
"Chicken Parmesan ":{"calories":600},
"Beef Braciole ":{"calories":400},
"Veal Marsala ":{"calories":400},
"Eggplant Parmesan ":{"calories":400},
"Minestrone Soup ":{"calories":150},
"Minestrone alla Genovese ":{"calories":200},
"Grilled Vegetables ":{"calories":150},
"Gnocchi ":{"calories":400},
"Polenta ":{"calories":350},
"Calamari Fritti ":{"calories":400},
"Beef Carpaccio ":{"calories":200},
"Gnocchi alla Sorrentina ":{"calories":600},
"Tiramisu ":{"calories":400}
}


for i in ingredients:
    print( '<li><a href="#" className="block w-full px-4 py-2 rounded-b-lg cursor-pointer hover:bg-gray-100 hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:text-blue-700 light:border-gray-600 light:hover:bg-gray-600 light:hover:text-white light:focus:ring-gray-500 light:focus:text-white" id="' + i + '">' +  i + '</a></li>')